# Generated by Django 3.2.9 on 2021-11-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'горячие блюда',
                'verbose_name_plural': 'горячие блюда',
                'db_table': 'Hot',
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'салаты',
                'verbose_name_plural': 'салаты',
                'db_table': 'Salad',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Спец предложения',
                'verbose_name_plural': 'Спец предложения',
                'db_table': 'Special',
            },
        ),
    ]
