# Generated by Django 3.2.9 on 2021-11-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_hot_salad_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Бар',
                'verbose_name_plural': 'Бар',
                'db_table': 'Bar',
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'десерт',
                'verbose_name_plural': 'десерт',
                'db_table': 'Dessert',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'телефон',
                'verbose_name_plural': 'телефон',
                'db_table': 'Phone',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'закуски',
                'verbose_name_plural': 'закуски',
                'db_table': 'snacks',
            },
        ),
    ]
