# Generated by Django 3.2.9 on 2021-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bar_dessert_phone_snacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'интерьер',
                'verbose_name_plural': 'интерьер',
                'db_table': 'Interior',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'место',
                'db_table': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команда',
                'db_table': 'Team',
            },
        ),
    ]
