# Generated by Django 3.2.9 on 2021-11-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_interior_place_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specially',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='images/', verbose_name='картинка горизонтальная')),
                ('image2', models.ImageField(blank=True, upload_to='images/', verbose_name='картинка квадрат')),
                ('image3', models.ImageField(blank=True, upload_to='images/', verbose_name='картинка вертикальная')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
            ],
            options={
                'verbose_name': 'Спец',
                'verbose_name_plural': 'Спец',
                'db_table': 'Specially',
            },
        ),
    ]
