# Generated by Django 3.2.9 on 2021-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_specially'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='ссылка картинки')),
                ('text', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'галерея',
                'db_table': 'Gallery',
            },
        ),
    ]
